#!/usr/bin/env bash
# migrate.sh — analyzes an existing repo and generates a MIGRATION.md guide
# Usage: bash cli/migrate.sh --variant website --target /path/to/existing/repo
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KIT_ROOT="$(dirname "$SCRIPT_DIR")"

VARIANT=""
TARGET=""
DRY_RUN=false

show_help() {
  cat << 'HELPEOF'
Usage: bash cli/migrate.sh --variant <variant> --target <path>

Analyzes an existing repo and generates a MIGRATION.md guide for adopting the kit.

Options:
  --variant <name>   Variant to migrate to (required)
  --target <path>    Path to existing repo (required)
  --dry-run          Show what would be analyzed without writing MIGRATION.md
  --help, -h         Show this help
HELPEOF
  exit 0
}

while [[ $# -gt 0 ]]; do
  case $1 in
    --variant)  VARIANT="$2"; shift 2 ;;
    --target)   TARGET="$2";  shift 2 ;;
    --dry-run)  DRY_RUN=true; shift ;;
    --help|-h)  show_help ;;
    *) echo "Unknown argument: $1. Use --help for usage."; exit 1 ;;
  esac
done

if [ -z "$VARIANT" ] || [ -z "$TARGET" ]; then
  echo "Usage: bash cli/migrate.sh --variant <variant> --target /path/to/repo"
  echo "Run with --help for more info."
  exit 1
fi

if [ ! -d "$TARGET" ]; then
  echo "Error: target directory '$TARGET' does not exist."
  exit 1
fi

echo ""
echo "project-starter-kit migrate"
echo "==========================="
echo "  Variant : $VARIANT"
echo "  Target  : $TARGET"
echo ""
echo "Analyzing existing repo..."

# ── Detect what's already present ─────────────────────────────────────────────
HAS_TESTS=false
HAS_LINTER=false
HAS_TYPES=false
HAS_CI=false
HAS_AGENTS_MD=false
HAS_CHANGES_MD=false
HAS_MAKEFILE=false
HAS_HOOKS=false
TEST_FRAMEWORK=""

[ -d "$TARGET/tests" ] || [ -d "$TARGET/test" ] || find "$TARGET/src" -name "*.test.*" -quit 2>/dev/null && HAS_TESTS=true
[ -f "$TARGET/.eslintrc*" ] || [ -f "$TARGET/eslint.config*" ] || [ -f "$TARGET/biome.json" ] && HAS_LINTER=true
[ -f "$TARGET/tsconfig.json" ] && HAS_TYPES=true
[ -d "$TARGET/.github/workflows" ] && HAS_CI=true
[ -f "$TARGET/AGENTS.md" ] && HAS_AGENTS_MD=true
[ -f "$TARGET/CHANGES.md" ] && HAS_CHANGES_MD=true
[ -f "$TARGET/Makefile" ] && HAS_MAKEFILE=true
[ -d "$TARGET/.claude/hooks" ] || [ -d "$TARGET/.opencode/hooks" ] && HAS_HOOKS=true
grep -q "vitest\|jest\|mocha" "$TARGET/package.json" 2>/dev/null && TEST_FRAMEWORK="found in package.json"

# ── Measure current LOC ───────────────────────────────────────────────────────
SRC_LOC=0
if [ -d "$TARGET/src" ]; then
  SRC_LOC=$(find "$TARGET/src" -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" 2>/dev/null | xargs wc -l 2>/dev/null | tail -1 | awk '{print $1}' || echo 0)
fi

# ── Dry run ───────────────────────────────────────────────────────────────────
if [ "$DRY_RUN" = true ]; then
  echo ""
  echo "[dry-run] Analysis results:"
  echo "  Tests:      $( $HAS_TESTS && echo "Yes ($TEST_FRAMEWORK)" || echo "No")"
  echo "  Linter:     $( $HAS_LINTER && echo "Yes" || echo "No")"
  echo "  TypeScript: $( $HAS_TYPES && echo "Yes" || echo "No")"
  echo "  CI/CD:      $( $HAS_CI && echo "Yes" || echo "No")"
  echo "  Source LOC: ~${SRC_LOC}"
  echo ""
  echo "[dry-run] Would write MIGRATION.md to $TARGET/MIGRATION.md"
  echo "[dry-run] No files were written."
  exit 0
fi

# ── Write MIGRATION.md ────────────────────────────────────────────────────────
MIGRATION_FILE="$TARGET/MIGRATION.md"

cat > "$MIGRATION_FILE" << EOF
# MIGRATION.md
Generated by project-starter-kit migrate on $(date +%Y-%m-%d).
This file is your agent's brief for adopting the starter kit into this project.

## Current state

| What | Present |
|------|---------|
| Tests | $( $HAS_TESTS && echo "Yes ($TEST_FRAMEWORK)" || echo "No") |
| Linter | $( $HAS_LINTER && echo "Yes" || echo "No") |
| TypeScript | $( $HAS_TYPES && echo "Yes" || echo "No") |
| CI/CD | $( $HAS_CI && echo "Yes") |
| AGENTS.md | $( $HAS_AGENTS_MD && echo "Yes (will be merged)" || echo "No") |
| CHANGES.md | $( $HAS_CHANGES_MD && echo "Yes" || echo "No") |
| Makefile | $( $HAS_MAKEFILE && echo "Yes (will be extended)" || echo "No") |
| Lifecycle hooks | $( $HAS_HOOKS && echo "Yes" || echo "No") |
| Source LOC | ~${SRC_LOC} |

## Migration steps (for your agent)

Work through these in order. Do not skip steps.

### Step 1 — Copy kit files (non-destructive)
The compose script copies files without overwriting existing ones.
\`\`\`bash
bash $SCRIPT_DIR/compose.sh --variant $VARIANT --mode lean --target $TARGET
\`\`\`
Start in lean mode to reduce friction. Upgrade to full once tests are green.

### Step 2 — Merge AGENTS.md
$( $HAS_AGENTS_MD && echo "You have an existing AGENTS.md. Merge your project-specific content into the kit's version. Keep kit structure (mode declaration, doc table, non-negotiable rules) — add your content after." || echo "No existing AGENTS.md. Fill in the project overview and tech stack sections in the kit's AGENTS.md.")

### Step 3 — Wire up Makefile targets
$( $HAS_MAKEFILE && echo "You have an existing Makefile. Add the kit's targets (\`check\`, \`health\`, \`analyze\`) to it, or replace it with the kit's version and port your existing targets." || echo "No Makefile found — the kit's Makefile is ready to use. Fill in the package manager and command names.")

### Step 4 — Run the health check
\`\`\`bash
cd $TARGET && bash scripts/health-check.sh
\`\`\`
Review the output. Fix hard failures before proceeding. Soft warnings can wait.

### Step 5 — Write the initial CHANGES.md entry
Add a migration entry documenting the current state of the project so future sessions
have a baseline. Use the format in \`.kit/changelog-protocol.md\`.

### Step 6 — Upgrade to full mode (when ready)
\`\`\`bash
bash $SCRIPT_DIR/upgrade.sh
\`\`\`

## Notes for the agent

- Do not modify source files during migration — only add kit infrastructure files
- If a kit file conflicts with an existing file, preserve the existing file and note the conflict here
- After migration, run \`make check\` and document what fails in this file
EOF

echo "✓ MIGRATION.md written to $TARGET/MIGRATION.md"
echo ""
echo "Next: open your agent and say:"
echo "  'Read MIGRATION.md and AGENTS.md, then work through the migration steps.'"
