#!/usr/bin/env bash
# analyze-changes.sh — reads CHANGES.md for dead code signals
# Called by pre-compact.sh before context compression.
# Outputs: dead code report to stdout, updates SESSION_SUMMARY.md
set -euo pipefail

CHANGES_FILE=${CHANGES_FILE:-CHANGES.md}
SUMMARY_FILE=${SUMMARY_FILE:-SESSION_SUMMARY.md}
SRC_DIR=${SRC_DIR:-src}
MAX_SESSIONS=${MAX_SESSIONS:-5}

if [ ! -f "$CHANGES_FILE" ]; then
  echo "No CHANGES.md found — skipping analysis."
  exit 0
fi

echo "==> Analyzing $CHANGES_FILE for dead code signals..."

# ── Extract all symbols_removed entries (from completed entries + progress lines) ─
mapfile -t removed_symbols < <(
  {
    # From completed entry symbols_removed fields
    sed -n '/<!-- Entries below/,$p' "$CHANGES_FILE" \
      | grep '^symbols_removed:' \
      | sed 's/^symbols_removed: //' \
      | tr ',' '\n'
    # From progress lines with (removed: ...) annotations
    sed -n '/<!-- Entries below/,$p' "$CHANGES_FILE" \
      | grep -oP '\(removed?: \K[^)]+' \
      | tr ',' '\n'
  } \
    | sed 's/^[[:space:]]*//' \
    | sed 's/[[:space:]]*$//' \
    | grep -v '^$' \
    | grep -v '^(none)$' \
    | grep -v '^(fill in)$' \
    | sort -u
)

echo "    Found ${#removed_symbols[@]} unique removed symbol(s) in history (completed entries + progress lines)."

# ── Check which removed symbols still appear in source ───────────────────────
echo ""
echo "==> Dead code check (removed symbols still in use):"

found_dead=0
dead_report=""

for sym in "${removed_symbols[@]}"; do
  [ -z "$sym" ] && continue
  # Search for the symbol as a word boundary match
  if grep -rq --include="*.ts" --include="*.tsx" --include="*.js" \
      "\b${sym}\b" "$SRC_DIR" 2>/dev/null; then
    locations=$(grep -rl --include="*.ts" --include="*.tsx" --include="*.js" \
      "\b${sym}\b" "$SRC_DIR" 2>/dev/null | head -3 | tr '\n' ', ' | sed 's/,$//')
    echo "  DEAD: '$sym' (removed in log but still found in: $locations)"
    dead_report="${dead_report}\n- \`${sym}\` — found in: ${locations}"
    found_dead=$((found_dead + 1))
  fi
done

if [ "$found_dead" -eq 0 ]; then
  echo "  No confirmed dead code found."
fi

# ── Extract recent sessions for summary ──────────────────────────────────────
echo ""
echo "==> Extracting last $MAX_SESSIONS sessions for SESSION_SUMMARY..."

recent_sessions=$(sed -n '/<!-- Entries below/,$p' "$CHANGES_FILE" | grep -A6 '^## \[' | tail -n "$((MAX_SESSIONS * 8))" || echo "(none)")

# ── Write SESSION_SUMMARY.md ─────────────────────────────────────────────────
health_snapshot=$(sed -n '/<!-- Entries below/,$p' "$CHANGES_FILE" | grep 'health_snapshot:' | tail -1 | sed 's/health_snapshot: //' || echo "unknown")

cat > "$SUMMARY_FILE" << EOF
# SESSION_SUMMARY.md
Auto-generated by analyze-changes.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ"). Do not edit manually.

---

## Current health
$health_snapshot

## Pending dead code
$([ "$found_dead" -gt 0 ] && printf "%b" "$dead_report" || echo "None detected.")

## Recent changes (last $MAX_SESSIONS sessions)
$recent_sessions

## Next steps
<!-- Agent: fill this in at session end before compacting -->
EOF

echo "SESSION_SUMMARY.md written."
echo ""
echo "Summary: $found_dead dead symbol(s) found, SESSION_SUMMARY.md updated."
