# Makefile — project-starter-kit base
# Default targets use Node.js + npm. For other stacks, Makefile.stack overrides
# the concrete commands while keeping the same target names.
# See docs/bring-your-own-stack.md for how to adapt this.

.PHONY: help dev build check ci test health deadcode lint format types verify analyze clean

# ── Stack adapter: include Makefile.stack if present ─────────────────────────
# Makefile.stack is auto-generated by compose.sh based on detected stack.
# It overrides PKG_MANAGER, RUN, and individual targets for non-JS stacks.
-include Makefile.stack

# ── Defaults (Node.js) — overridden by Makefile.stack if present ─────────────
PKG_MANAGER ?= npm
RUN ?= $(PKG_MANAGER) run

## ── Meta ─────────────────────────────────────────────────────────────────────

help: ## Show all available targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'

## ── Development ──────────────────────────────────────────────────────────────

dev: ## Start development server
	$(RUN) dev

build: ## Build for production
	$(RUN) build

## ── Quality pipeline ─────────────────────────────────────────────────────────

check: format lint types deadcode test health verify ## Full quality pipeline (run before marking work done)
	@echo ""
	@echo "✓ All checks passed"

ci: check build ## Full CI pipeline (check + build)

## ── Individual checks ────────────────────────────────────────────────────────

format: ## Auto-format with Prettier (or Biome)
	$(RUN) format 2>/dev/null || npx prettier --write . --log-level warn

lint: ## Lint with ESLint (includes complexity rules)
	$(RUN) lint

types: ## TypeScript type check
	$(RUN) typecheck 2>/dev/null || npx tsc --noEmit

deadcode: ## Detect unused exports, files, dependencies (knip)
	$(RUN) deadcode 2>/dev/null || npx knip

test: ## Run all tests (Tier 1 + Tier 2 architecture tests)
	$(RUN) test

test-feature: ## Run feature tests only (Tier 1)
	$(RUN) test --reporter=verbose 2>/dev/null || npx vitest run

test-arch: ## Run architecture tests only (Tier 2)
	npx vitest run tests/architecture/

health: ## Run code health check (file size, LOC budget, console.log)
	@bash scripts/health-check.sh

## ── Changelog + context ──────────────────────────────────────────────────────

verify: ## Verify CHANGES.md: test coverage, regression tests, hotspots
	@bash scripts/verify-changes.sh

analyze: ## Analyze CHANGES.md for dead code signals, update SESSION_SUMMARY.md
	@bash scripts/analyze-changes.sh

## ── Cleanup ──────────────────────────────────────────────────────────────────

clean: ## Remove build artifacts
	rm -rf dist build .next out coverage
